#!/bin/bash
# IoT Space - Mosquitto MQTT Broker Setup
# Run as root or with sudo
# Usage: sudo bash setup-mosquitto.sh
#
# Sets up Mosquitto with:
# - Password authentication
# - TLS encryption (uses Let's Encrypt certs)
# - Listener on port 1883 (plain) and 8883 (TLS)

set -e

DOMAIN="api.spaceautotech.com"
MQTT_USER="iotspace"
MQTT_PASS_FILE="/etc/mosquitto/passwd"
MQTT_CONF="/etc/mosquitto/conf.d/iotspace.conf"

echo "=========================================="
echo "  IoT Space - Mosquitto MQTT Setup"
echo "=========================================="

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root (sudo bash setup-mosquitto.sh)"
  exit 1
fi

# Check if mosquitto is installed
if ! command -v mosquitto &> /dev/null; then
  echo "Mosquitto not found. Installing..."
  apt-get update && apt-get install -y mosquitto mosquitto-clients
fi

# Stop mosquitto while configuring
systemctl stop mosquitto

# Create MQTT password
echo "[1/4] Setting up MQTT authentication..."
echo "Enter a password for MQTT user '$MQTT_USER':"
mosquitto_passwd -c "$MQTT_PASS_FILE" "$MQTT_USER"
chmod 600 "$MQTT_PASS_FILE"

# Check if SSL certs exist
HAS_TLS=false
if [ -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]; then
  HAS_TLS=true
  echo "[2/4] SSL certificates found - enabling TLS listener"
else
  echo "[2/4] No SSL certificates found - skipping TLS listener"
  echo "  Run setup-ssl.sh first, then re-run this script to enable TLS"
fi

# Create Mosquitto configuration
echo "[3/4] Writing Mosquitto configuration..."
cat > "$MQTT_CONF" << EOF
# IoT Space - Mosquitto Configuration
# Generated by setup-mosquitto.sh

# Disable anonymous access
allow_anonymous false
password_file $MQTT_PASS_FILE

# Plain MQTT listener (for local/internal use)
listener 1883 0.0.0.0
protocol mqtt

# Logging
log_dest file /var/log/mosquitto/mosquitto.log
log_type all
connection_messages true
log_timestamp true

# Performance
max_connections 100
message_size_limit 10240
EOF

# Add TLS listener if certs are available
if [ "$HAS_TLS" = true ]; then
  cat >> "$MQTT_CONF" << EOF

# TLS MQTT listener (for external/device connections)
listener 8883 0.0.0.0
protocol mqtt
cafile /etc/letsencrypt/live/$DOMAIN/chain.pem
certfile /etc/letsencrypt/live/$DOMAIN/fullchain.pem
keyfile /etc/letsencrypt/live/$DOMAIN/privkey.pem
tls_version tlsv1.2
EOF

  # Grant mosquitto access to Let's Encrypt certs
  usermod -aG ssl-cert mosquitto 2>/dev/null || true
  chmod 750 /etc/letsencrypt/live/
  chmod 750 /etc/letsencrypt/archive/
  chgrp -R ssl-cert /etc/letsencrypt/live/ 2>/dev/null || true
  chgrp -R ssl-cert /etc/letsencrypt/archive/ 2>/dev/null || true
fi

# Create log directory
mkdir -p /var/log/mosquitto
chown mosquitto:mosquitto /var/log/mosquitto

# Start Mosquitto
echo "[4/4] Starting Mosquitto..."
systemctl start mosquitto
systemctl enable mosquitto

# Verify it's running
sleep 2
if systemctl is-active --quiet mosquitto; then
  echo ""
  echo "=========================================="
  echo "  Mosquitto MQTT Setup Complete!"
  echo "=========================================="
  echo ""
  echo "MQTT Broker is running:"
  echo "  - Plain:  mqtt://$DOMAIN:1883"
  if [ "$HAS_TLS" = true ]; then
    echo "  - TLS:    mqtts://$DOMAIN:8883"
  fi
  echo ""
  echo "Credentials:"
  echo "  - User: $MQTT_USER"
  echo "  - Pass: (the password you just set)"
  echo ""
  echo "Test connection:"
  echo "  mosquitto_sub -h localhost -u $MQTT_USER -P <password> -t 'test/#' -v"
  echo "  mosquitto_pub -h localhost -u $MQTT_USER -P <password> -t 'test/hello' -m 'world'"
  echo ""
  echo "For .env.production, set:"
  echo "  MQTT_BROKER_URL=mqtt://localhost:1883"
  echo "  MQTT_USERNAME=$MQTT_USER"
  echo "  MQTT_PASSWORD=<your-password>"
  echo ""
else
  echo "ERROR: Mosquitto failed to start. Check logs:"
  echo "  journalctl -u mosquitto -n 20"
  exit 1
fi
